name: Rapid scan test

on:
   workflow_dispatch:
     
jobs: 

  rapid_scan:
    runs-on: [ small ]
    strategy:
      matrix:
        node-version: [20.x]
        
  #  needs: [Rapid-Scan]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
           always-auth: true
           registry-url: 'https://artifacts.i.mercedes-benz.com/artifactory/api/npm/switch-main-npm-releases/'
           scope: '@mercedes-benz'
           node-version: ${{ matrix.node-version }}
           cache: 'npm' 
         
      - name: Install dependencies
        run : npm install --legacy-peer-deps
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin' 

      - name: Black Duck Scan
        uses: blackduck-inc/black-duck-security-scan@v2.1.0
        env:
          DETECT_PROJECT_NAME: "BD-SCAN-DANIEL"
          DETECT_PROJECT_VERSION_NAME: "1.0"
          DETECT_TIMEOUT: "1800"
          BLACKDUCK_TRUST_CERT: true
            
        with:
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_scan_full: false
          blackducksca_scan_failure_severities: BLOCKER,CRITICAL,MAJOR
          mark_build_status: success
          blackducksca_fixpr_useUpgradeGuidance: SHORT_TERM,LONG_TERM

           
    
           
        
