name: CI-BlackDuck-SCA-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Black Duck SCA Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: Daniel-SCA-Test
          DETECT_PROJECT_VERSION_NAME: 1.0
          DETECT_BLACKDUCK_SIGNATURE_SCANNER_SNIPPET_MATCHING: SNIPPET_MATCHING
          BLACKDUCK_TRUST_CERT: true
          DETECT_DETECTOR_SEARCH_DEPTH: 15
          DETECT_CODE_LOCATION_NAME: testbdionametesting
          BRIDGE_DETECT_ARGS: --detect.bdio.file.name=DanielBDTEst --detect.blackduck.scan.mode=RAPID
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_scan_full: true

         

