name: Black Duck Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  blackduck_sca_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java (Required for Synopsys Detect)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Black Duck Security Scan
        run: |
          bash <(curl -s https://detect.blackduck.com/detect.sh) \
            --blackduck.url="${{ secrets.BLACKDUCK_URL }}" \
            --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN }}" \
            --detect.project.name="Daniel_Github_Actions" \
            --detect.project.version.name="1.0.0" \
            --detect.code.location.name="MyProject-Scan" 

