name: Synopsys Security Action
on:
  workflow_dispatch:
  push:
  pull_request:
     branches:
     - main

jobs:
  build:

    runs-on: [ road-runner ] 
    steps:
     - uses: actions/checkout@v2
     - name: Set up Java 11
       uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
     - name: setup python
       uses: actions/setup-python@v2
       with:
         python-version: '3.9'
         
     - name: Install libraries
       run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
     - name: Black Duck SCA Scan
       uses: blackduck-inc/black-duck-security-scan@v2.0.0
       
       env:
            DETECT_PROJECT_NAME: test-Daniel
            DETECT_PROJECT_VERSION_NAME: PR-TEST
            BRIDGE_BLACKDUCKSCA_FIXPR_ENABLED: true
            
       with:
          blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_scan_full: true
          blackducksca_scan_failure_severities: ALL
