name: Black Duck Rapid Upload

on:
  push:
    branches:
      - main

jobs:
  blackduck-rapid-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Specify the Java distribution (e.g., adopt, zulu, temurin)
        java-version: '11'

    - name: Install Detect script
      run: |
        curl -s -L https://detect.blackduck.com/detect10.sh -o detect10.sh  # Updated URL
        cat detect10.sh  # Add this line to print the content of the downloaded script

    - name: Verify Detect script
      run: |
        file detect10.sh  # Verify the file type

    - name: Run Black Duck Detect for Rapid Upload
      env:
        BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
        BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        VERSION_NAME: ${{ secrets.VERSION_NAME }}
      run: |
        bash detect10.sh \ 
          --blackduck.url=$BLACKDUCK_URL \
          --blackduck.api.token=$BLACKDUCK_API_TOKEN \
          --detect.project.name=$PROJECT_NAME \
          --detect.project.version.name=$VERSION_NAME \
          --detect.code.location.name=testbdionametesting \
          --detect.bdio.output.path=. \
          --detect.bdio.file.name=test-raks
